/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MonthlyIncomeInput = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'amount' : IDL.Int,
});
export const PaymentMethod = IDL.Variant({
  'kartica' : IDL.Null,
  'gotovina' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'prihod' : IDL.Null,
  'rashod' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'rezije' : IDL.Null,
  'oprema' : IDL.Null,
  'napojnica' : IDL.Null,
  'pice' : IDL.Null,
  'place' : IDL.Null,
  'ostalo' : IDL.Null,
  'namirnice' : IDL.Null,
});
export const TransactionInput = IDL.Record({
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'transactionType' : TransactionType,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Int,
  'expenseCategory' : IDL.Opt(ExpenseCategory),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OfferType = IDL.Variant({
  'bar' : IDL.Null,
  'brzaHrana' : IDL.Null,
  'kafic' : IDL.Null,
  'ostalo' : IDL.Null,
  'restoran' : IDL.Null,
});
export const SeasonalActivity = IDL.Variant({
  'oboje' : IDL.Null,
  'zima' : IDL.Null,
  'ljeto' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'offerType' : OfferType,
  'seasonalActivity' : SeasonalActivity,
  'numberOfSeats' : IDL.Nat,
  'location' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'transactionType' : TransactionType,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Int,
  'expenseCategory' : IDL.Opt(ExpenseCategory),
});
export const ExportData = IDL.Record({
  'monthlyIncomes' : IDL.Vec(MonthlyIncomeInput),
  'businessProfile' : IDL.Opt(BusinessProfile),
  'transactions' : IDL.Vec(Transaction),
});
export const BenchmarkPeriod = IDL.Variant({
  'cumulative' : IDL.Null,
  'monthly' : IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat }),
  'yearly' : IDL.Record({ 'year' : IDL.Nat }),
});
export const DeviationStatus = IDL.Variant({
  'withinNormalRange' : IDL.Null,
  'belowAverage' : IDL.Null,
  'aboveAverage' : IDL.Null,
});
export const PerformanceDeviation = IDL.Record({
  'status' : DeviationStatus,
  'industryAverage' : IDL.Int,
  'deviationPercentage' : IDL.Float64,
  'category' : IDL.Text,
  'userValue' : IDL.Int,
});
export const IndustryBenchmark = IDL.Record({
  'revenuePerSeat' : IDL.Opt(IDL.Int),
  'averageIncome' : IDL.Int,
  'averageExpenses' : IDL.Int,
  'averageProfitMargin' : IDL.Float64,
  'expenseCategoryAverages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
});
export const PerformanceAnalysis = IDL.Record({
  'diagnosticInfo' : IDL.Opt(IDL.Text),
  'period' : BenchmarkPeriod,
  'recommendations' : IDL.Vec(IDL.Text),
  'profitMarginDeviation' : PerformanceDeviation,
  'industryBenchmark' : IndustryBenchmark,
  'userIncome' : IDL.Int,
  'userProfit' : IDL.Int,
  'userExpenses' : IDL.Int,
  'incomeDeviation' : PerformanceDeviation,
  'expenseDeviations' : IDL.Vec(PerformanceDeviation),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'restaurantName' : IDL.Text,
});
export const DfinityTechnicalAnalysis = IDL.Record({
  'title' : IDL.Text,
  'issueDescription' : IDL.Text,
  'userExperienceImpact' : IDL.Text,
  'recommendations' : IDL.Text,
  'conclusion' : IDL.Text,
  'dataPersistenceFindings' : IDL.Text,
  'executiveSummary' : IDL.Text,
  'recoveryAttempts' : IDL.Text,
  'technicalAnalysis' : IDL.Text,
});
export const DfinityTechnicalReport = IDL.Record({
  'title' : IDL.Text,
  'synchronizationImprovements' : IDL.Text,
  'dateBoundaryHandling' : IDL.Text,
  'summary' : IDL.Text,
  'decimalPrecision' : IDL.Text,
  'confirmation' : IDL.Text,
  'consistencyVerification' : IDL.Text,
  'finalVerification' : IDL.Text,
});
export const DfinityVoiceCommandIssueReport = IDL.Record({
  'title' : IDL.Text,
  'authenticationIntegrationProblems' : IDL.Text,
  'implementationAttemptHistory' : IDL.Text,
  'browserCompatibilityIssues' : IDL.Text,
  'conclusion' : IDL.Text,
  'rootCauseIdentification' : IDL.Text,
  'technicalIssueAnalysis' : IDL.Text,
  'introduction' : IDL.Text,
  'comparativeAnalysis' : IDL.Text,
  'connectivityPatternAnalysis' : IDL.Text,
  'implementationTimeline' : IDL.Text,
  'platformRecommendations' : IDL.Text,
  'technicalArchitectureReview' : IDL.Text,
});
export const ExpenseShare = IDL.Record({
  'total' : IDL.Int,
  'share' : IDL.Float64,
  'category' : IDL.Text,
});
export const MonthlyIncomeExpense = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'totalIncome' : IDL.Int,
  'totalExpenses' : IDL.Int,
});
export const FinancialOverview = IDL.Record({
  'totalIncome' : IDL.Int,
  'totalExpenses' : IDL.Int,
  'profit' : IDL.Int,
});
export const CategorySummary = IDL.Record({
  'total' : IDL.Int,
  'category' : IDL.Text,
});
export const PaymentMethodSummary = IDL.Record({
  'total' : IDL.Int,
  'paymentMethod' : IDL.Text,
});
export const MonthlyReport = IDL.Record({
  'month' : IDL.Nat,
  'expensesByCategory' : IDL.Vec(CategorySummary),
  'overview' : FinancialOverview,
  'year' : IDL.Nat,
  'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
});
export const PdfReportData = IDL.Record({
  'monthlyIncomes' : IDL.Vec(MonthlyIncomeInput),
  'expensesByCategory' : IDL.Vec(CategorySummary),
  'overview' : FinancialOverview,
  'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
  'businessProfile' : IDL.Opt(BusinessProfile),
  'transactions' : IDL.Vec(Transaction),
});
export const Projection = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'projectedIncome' : IDL.Int,
  'projectedProfit' : IDL.Int,
  'projectedExpenses' : IDL.Int,
});
export const YearComparison = IDL.Record({
  'year' : IDL.Nat,
  'totalIncome' : IDL.Int,
  'totalExpenses' : IDL.Int,
  'monthlyData' : IDL.Vec(MonthlyIncomeExpense),
});
export const YearlyReport = IDL.Record({
  'monthlyOverviews' : IDL.Vec(FinancialOverview),
  'year' : IDL.Nat,
  'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
  'totalOverview' : FinancialOverview,
});
export const SimulationResult = IDL.Record({
  'totalProjectedExpenses' : IDL.Int,
  'projections' : IDL.Vec(Projection),
  'totalProjectedIncome' : IDL.Int,
  'totalProjectedProfit' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMonthlyIncome' : IDL.Func([MonthlyIncomeInput], [], []),
  'addTransaction' : IDL.Func([TransactionInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authorizeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
  'deleteMonthlyIncome' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'exportData' : IDL.Func([], [ExportData], ['query']),
  'getAllBusinessProfilesReadOnly' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessProfile))],
      ['query'],
    ),
  'getAllMonthlyIncomes' : IDL.Func(
      [],
      [IDL.Vec(MonthlyIncomeInput)],
      ['query'],
    ),
  'getAllMonthlyIncomesReadOnly' : IDL.Func(
      [],
      [IDL.Vec(MonthlyIncomeInput)],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllTransactionsReadOnly' : IDL.Func(
      [],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getBusinessPerformanceAnalysis' : IDL.Func(
      [BenchmarkPeriod],
      [PerformanceAnalysis],
      ['query'],
    ),
  'getBusinessProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerBusinessProfile' : IDL.Func(
      [],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getDfinityTechnicalAnalysis' : IDL.Func(
      [],
      [DfinityTechnicalAnalysis],
      ['query'],
    ),
  'getDfinityTechnicalReport' : IDL.Func(
      [],
      [DfinityTechnicalReport],
      ['query'],
    ),
  'getDfinityVoiceCommandIssueReport' : IDL.Func(
      [],
      [DfinityVoiceCommandIssueReport],
      ['query'],
    ),
  'getExpenseShareByCategory' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ExpenseShare)],
      ['query'],
    ),
  'getMonthlyIncome' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Int], ['query']),
  'getMonthlyIncomeCount' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getMonthlyIncomeExpenseByYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MonthlyIncomeExpense)],
      ['query'],
    ),
  'getMonthlyOverview' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [FinancialOverview],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyReport], ['query']),
  'getPdfFinancialReportData' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [PdfReportData],
      ['query'],
    ),
  'getPredictiveAnalysis' : IDL.Func(
      [],
      [
        IDL.Record({
          'projections' : IDL.Vec(Projection),
          'historicalData' : IDL.Vec(
            IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Int, IDL.Int)
          ),
        }),
      ],
      ['query'],
    ),
  'getTotalMonthlyIncome' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Int], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactionCountsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTransactionsByCategory' : IDL.Func(
      [TransactionType, IDL.Opt(ExpenseCategory)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByFilters' : IDL.Func(
      [
        IDL.Opt(TransactionType),
        IDL.Opt(ExpenseCategory),
        IDL.Opt(PaymentMethod),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByPaymentMethod' : IDL.Func(
      [PaymentMethod],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearComparison' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(YearComparison)],
      ['query'],
    ),
  'getYearlyOverview' : IDL.Func([IDL.Nat], [FinancialOverview], ['query']),
  'getYearlyReport' : IDL.Func([IDL.Nat], [YearlyReport], ['query']),
  'hasCallerReadOnlyAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isWakeUpRoutineActive' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
  'runSimulation' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [SimulationResult],
      ['query'],
    ),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startWakeUpRoutine' : IDL.Func([], [], []),
  'updateMonthlyIncome' : IDL.Func([MonthlyIncomeInput], [], []),
  'updateTransaction' : IDL.Func([IDL.Nat, TransactionInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MonthlyIncomeInput = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'amount' : IDL.Int,
  });
  const PaymentMethod = IDL.Variant({
    'kartica' : IDL.Null,
    'gotovina' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'prihod' : IDL.Null,
    'rashod' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'rezije' : IDL.Null,
    'oprema' : IDL.Null,
    'napojnica' : IDL.Null,
    'pice' : IDL.Null,
    'place' : IDL.Null,
    'ostalo' : IDL.Null,
    'namirnice' : IDL.Null,
  });
  const TransactionInput = IDL.Record({
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'transactionType' : TransactionType,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Int,
    'expenseCategory' : IDL.Opt(ExpenseCategory),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OfferType = IDL.Variant({
    'bar' : IDL.Null,
    'brzaHrana' : IDL.Null,
    'kafic' : IDL.Null,
    'ostalo' : IDL.Null,
    'restoran' : IDL.Null,
  });
  const SeasonalActivity = IDL.Variant({
    'oboje' : IDL.Null,
    'zima' : IDL.Null,
    'ljeto' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'offerType' : OfferType,
    'seasonalActivity' : SeasonalActivity,
    'numberOfSeats' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'transactionType' : TransactionType,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Int,
    'expenseCategory' : IDL.Opt(ExpenseCategory),
  });
  const ExportData = IDL.Record({
    'monthlyIncomes' : IDL.Vec(MonthlyIncomeInput),
    'businessProfile' : IDL.Opt(BusinessProfile),
    'transactions' : IDL.Vec(Transaction),
  });
  const BenchmarkPeriod = IDL.Variant({
    'cumulative' : IDL.Null,
    'monthly' : IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat }),
    'yearly' : IDL.Record({ 'year' : IDL.Nat }),
  });
  const DeviationStatus = IDL.Variant({
    'withinNormalRange' : IDL.Null,
    'belowAverage' : IDL.Null,
    'aboveAverage' : IDL.Null,
  });
  const PerformanceDeviation = IDL.Record({
    'status' : DeviationStatus,
    'industryAverage' : IDL.Int,
    'deviationPercentage' : IDL.Float64,
    'category' : IDL.Text,
    'userValue' : IDL.Int,
  });
  const IndustryBenchmark = IDL.Record({
    'revenuePerSeat' : IDL.Opt(IDL.Int),
    'averageIncome' : IDL.Int,
    'averageExpenses' : IDL.Int,
    'averageProfitMargin' : IDL.Float64,
    'expenseCategoryAverages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  });
  const PerformanceAnalysis = IDL.Record({
    'diagnosticInfo' : IDL.Opt(IDL.Text),
    'period' : BenchmarkPeriod,
    'recommendations' : IDL.Vec(IDL.Text),
    'profitMarginDeviation' : PerformanceDeviation,
    'industryBenchmark' : IndustryBenchmark,
    'userIncome' : IDL.Int,
    'userProfit' : IDL.Int,
    'userExpenses' : IDL.Int,
    'incomeDeviation' : PerformanceDeviation,
    'expenseDeviations' : IDL.Vec(PerformanceDeviation),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  const DfinityTechnicalAnalysis = IDL.Record({
    'title' : IDL.Text,
    'issueDescription' : IDL.Text,
    'userExperienceImpact' : IDL.Text,
    'recommendations' : IDL.Text,
    'conclusion' : IDL.Text,
    'dataPersistenceFindings' : IDL.Text,
    'executiveSummary' : IDL.Text,
    'recoveryAttempts' : IDL.Text,
    'technicalAnalysis' : IDL.Text,
  });
  const DfinityTechnicalReport = IDL.Record({
    'title' : IDL.Text,
    'synchronizationImprovements' : IDL.Text,
    'dateBoundaryHandling' : IDL.Text,
    'summary' : IDL.Text,
    'decimalPrecision' : IDL.Text,
    'confirmation' : IDL.Text,
    'consistencyVerification' : IDL.Text,
    'finalVerification' : IDL.Text,
  });
  const DfinityVoiceCommandIssueReport = IDL.Record({
    'title' : IDL.Text,
    'authenticationIntegrationProblems' : IDL.Text,
    'implementationAttemptHistory' : IDL.Text,
    'browserCompatibilityIssues' : IDL.Text,
    'conclusion' : IDL.Text,
    'rootCauseIdentification' : IDL.Text,
    'technicalIssueAnalysis' : IDL.Text,
    'introduction' : IDL.Text,
    'comparativeAnalysis' : IDL.Text,
    'connectivityPatternAnalysis' : IDL.Text,
    'implementationTimeline' : IDL.Text,
    'platformRecommendations' : IDL.Text,
    'technicalArchitectureReview' : IDL.Text,
  });
  const ExpenseShare = IDL.Record({
    'total' : IDL.Int,
    'share' : IDL.Float64,
    'category' : IDL.Text,
  });
  const MonthlyIncomeExpense = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'totalIncome' : IDL.Int,
    'totalExpenses' : IDL.Int,
  });
  const FinancialOverview = IDL.Record({
    'totalIncome' : IDL.Int,
    'totalExpenses' : IDL.Int,
    'profit' : IDL.Int,
  });
  const CategorySummary = IDL.Record({
    'total' : IDL.Int,
    'category' : IDL.Text,
  });
  const PaymentMethodSummary = IDL.Record({
    'total' : IDL.Int,
    'paymentMethod' : IDL.Text,
  });
  const MonthlyReport = IDL.Record({
    'month' : IDL.Nat,
    'expensesByCategory' : IDL.Vec(CategorySummary),
    'overview' : FinancialOverview,
    'year' : IDL.Nat,
    'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
  });
  const PdfReportData = IDL.Record({
    'monthlyIncomes' : IDL.Vec(MonthlyIncomeInput),
    'expensesByCategory' : IDL.Vec(CategorySummary),
    'overview' : FinancialOverview,
    'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
    'businessProfile' : IDL.Opt(BusinessProfile),
    'transactions' : IDL.Vec(Transaction),
  });
  const Projection = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'projectedIncome' : IDL.Int,
    'projectedProfit' : IDL.Int,
    'projectedExpenses' : IDL.Int,
  });
  const YearComparison = IDL.Record({
    'year' : IDL.Nat,
    'totalIncome' : IDL.Int,
    'totalExpenses' : IDL.Int,
    'monthlyData' : IDL.Vec(MonthlyIncomeExpense),
  });
  const YearlyReport = IDL.Record({
    'monthlyOverviews' : IDL.Vec(FinancialOverview),
    'year' : IDL.Nat,
    'incomeByPaymentMethod' : IDL.Vec(PaymentMethodSummary),
    'totalOverview' : FinancialOverview,
  });
  const SimulationResult = IDL.Record({
    'totalProjectedExpenses' : IDL.Int,
    'projections' : IDL.Vec(Projection),
    'totalProjectedIncome' : IDL.Int,
    'totalProjectedProfit' : IDL.Int,
  });
  
  return IDL.Service({
    'addMonthlyIncome' : IDL.Func([MonthlyIncomeInput], [], []),
    'addTransaction' : IDL.Func([TransactionInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authorizeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
    'deleteMonthlyIncome' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'exportData' : IDL.Func([], [ExportData], ['query']),
    'getAllBusinessProfilesReadOnly' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessProfile))],
        ['query'],
      ),
    'getAllMonthlyIncomes' : IDL.Func(
        [],
        [IDL.Vec(MonthlyIncomeInput)],
        ['query'],
      ),
    'getAllMonthlyIncomesReadOnly' : IDL.Func(
        [],
        [IDL.Vec(MonthlyIncomeInput)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllTransactionsReadOnly' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getBusinessPerformanceAnalysis' : IDL.Func(
        [BenchmarkPeriod],
        [PerformanceAnalysis],
        ['query'],
      ),
    'getBusinessProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerBusinessProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getDfinityTechnicalAnalysis' : IDL.Func(
        [],
        [DfinityTechnicalAnalysis],
        ['query'],
      ),
    'getDfinityTechnicalReport' : IDL.Func(
        [],
        [DfinityTechnicalReport],
        ['query'],
      ),
    'getDfinityVoiceCommandIssueReport' : IDL.Func(
        [],
        [DfinityVoiceCommandIssueReport],
        ['query'],
      ),
    'getExpenseShareByCategory' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ExpenseShare)],
        ['query'],
      ),
    'getMonthlyIncome' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Int], ['query']),
    'getMonthlyIncomeCount' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getMonthlyIncomeExpenseByYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyIncomeExpense)],
        ['query'],
      ),
    'getMonthlyOverview' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [FinancialOverview],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyReport],
        ['query'],
      ),
    'getPdfFinancialReportData' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [PdfReportData],
        ['query'],
      ),
    'getPredictiveAnalysis' : IDL.Func(
        [],
        [
          IDL.Record({
            'projections' : IDL.Vec(Projection),
            'historicalData' : IDL.Vec(
              IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Int, IDL.Int)
            ),
          }),
        ],
        ['query'],
      ),
    'getTotalMonthlyIncome' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Int],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getTransactionCountsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTransactionsByCategory' : IDL.Func(
        [TransactionType, IDL.Opt(ExpenseCategory)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByFilters' : IDL.Func(
        [
          IDL.Opt(TransactionType),
          IDL.Opt(ExpenseCategory),
          IDL.Opt(PaymentMethod),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByPaymentMethod' : IDL.Func(
        [PaymentMethod],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearComparison' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(YearComparison)],
        ['query'],
      ),
    'getYearlyOverview' : IDL.Func([IDL.Nat], [FinancialOverview], ['query']),
    'getYearlyReport' : IDL.Func([IDL.Nat], [YearlyReport], ['query']),
    'hasCallerReadOnlyAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isWakeUpRoutineActive' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
    'runSimulation' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [SimulationResult],
        ['query'],
      ),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startWakeUpRoutine' : IDL.Func([], [], []),
    'updateMonthlyIncome' : IDL.Func([MonthlyIncomeInput], [], []),
    'updateTransaction' : IDL.Func([IDL.Nat, TransactionInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };