/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BenchmarkPeriod = { 'cumulative' : null } |
  { 'monthly' : { 'month' : bigint, 'year' : bigint } } |
  { 'yearly' : { 'year' : bigint } };
export interface BusinessProfile {
  'offerType' : OfferType,
  'seasonalActivity' : SeasonalActivity,
  'numberOfSeats' : bigint,
  'location' : string,
}
export interface CategorySummary { 'total' : bigint, 'category' : string }
export type DeviationStatus = { 'withinNormalRange' : null } |
  { 'belowAverage' : null } |
  { 'aboveAverage' : null };
export interface DfinityTechnicalAnalysis {
  'title' : string,
  'issueDescription' : string,
  'userExperienceImpact' : string,
  'recommendations' : string,
  'conclusion' : string,
  'dataPersistenceFindings' : string,
  'executiveSummary' : string,
  'recoveryAttempts' : string,
  'technicalAnalysis' : string,
}
export interface DfinityTechnicalReport {
  'title' : string,
  'synchronizationImprovements' : string,
  'dateBoundaryHandling' : string,
  'summary' : string,
  'decimalPrecision' : string,
  'confirmation' : string,
  'consistencyVerification' : string,
  'finalVerification' : string,
}
export interface DfinityVoiceCommandIssueReport {
  'title' : string,
  'authenticationIntegrationProblems' : string,
  'implementationAttemptHistory' : string,
  'browserCompatibilityIssues' : string,
  'conclusion' : string,
  'rootCauseIdentification' : string,
  'technicalIssueAnalysis' : string,
  'introduction' : string,
  'comparativeAnalysis' : string,
  'connectivityPatternAnalysis' : string,
  'implementationTimeline' : string,
  'platformRecommendations' : string,
  'technicalArchitectureReview' : string,
}
export type ExpenseCategory = { 'rezije' : null } |
  { 'oprema' : null } |
  { 'napojnica' : null } |
  { 'pice' : null } |
  { 'place' : null } |
  { 'ostalo' : null } |
  { 'namirnice' : null };
export interface ExpenseShare {
  'total' : bigint,
  'share' : number,
  'category' : string,
}
export interface ExportData {
  'monthlyIncomes' : Array<MonthlyIncomeInput>,
  'businessProfile' : [] | [BusinessProfile],
  'transactions' : Array<Transaction>,
}
export interface FinancialOverview {
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'profit' : bigint,
}
export interface IndustryBenchmark {
  'revenuePerSeat' : [] | [bigint],
  'averageIncome' : bigint,
  'averageExpenses' : bigint,
  'averageProfitMargin' : number,
  'expenseCategoryAverages' : Array<[string, bigint]>,
}
export interface MonthlyIncomeExpense {
  'month' : bigint,
  'year' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
}
export interface MonthlyIncomeInput {
  'month' : bigint,
  'year' : bigint,
  'amount' : bigint,
}
export interface MonthlyReport {
  'month' : bigint,
  'expensesByCategory' : Array<CategorySummary>,
  'overview' : FinancialOverview,
  'year' : bigint,
  'incomeByPaymentMethod' : Array<PaymentMethodSummary>,
}
export type OfferType = { 'bar' : null } |
  { 'brzaHrana' : null } |
  { 'kafic' : null } |
  { 'ostalo' : null } |
  { 'restoran' : null };
export type PaymentMethod = { 'kartica' : null } |
  { 'gotovina' : null };
export interface PaymentMethodSummary {
  'total' : bigint,
  'paymentMethod' : string,
}
export interface PdfReportData {
  'monthlyIncomes' : Array<MonthlyIncomeInput>,
  'expensesByCategory' : Array<CategorySummary>,
  'overview' : FinancialOverview,
  'incomeByPaymentMethod' : Array<PaymentMethodSummary>,
  'businessProfile' : [] | [BusinessProfile],
  'transactions' : Array<Transaction>,
}
export interface PerformanceAnalysis {
  'diagnosticInfo' : [] | [string],
  'period' : BenchmarkPeriod,
  'recommendations' : Array<string>,
  'profitMarginDeviation' : PerformanceDeviation,
  'industryBenchmark' : IndustryBenchmark,
  'userIncome' : bigint,
  'userProfit' : bigint,
  'userExpenses' : bigint,
  'incomeDeviation' : PerformanceDeviation,
  'expenseDeviations' : Array<PerformanceDeviation>,
}
export interface PerformanceDeviation {
  'status' : DeviationStatus,
  'industryAverage' : bigint,
  'deviationPercentage' : number,
  'category' : string,
  'userValue' : bigint,
}
export interface Projection {
  'month' : bigint,
  'year' : bigint,
  'projectedIncome' : bigint,
  'projectedProfit' : bigint,
  'projectedExpenses' : bigint,
}
export type SeasonalActivity = { 'oboje' : null } |
  { 'zima' : null } |
  { 'ljeto' : null };
export interface SimulationResult {
  'totalProjectedExpenses' : bigint,
  'projections' : Array<Projection>,
  'totalProjectedIncome' : bigint,
  'totalProjectedProfit' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'paymentMethod' : [] | [PaymentMethod],
  'transactionType' : TransactionType,
  'date' : bigint,
  'description' : string,
  'amount' : bigint,
  'expenseCategory' : [] | [ExpenseCategory],
}
export interface TransactionInput {
  'paymentMethod' : [] | [PaymentMethod],
  'transactionType' : TransactionType,
  'date' : bigint,
  'description' : string,
  'amount' : bigint,
  'expenseCategory' : [] | [ExpenseCategory],
}
export type TransactionType = { 'prihod' : null } |
  { 'rashod' : null };
export interface UserProfile { 'name' : string, 'restaurantName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YearComparison {
  'year' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'monthlyData' : Array<MonthlyIncomeExpense>,
}
export interface YearlyReport {
  'monthlyOverviews' : Array<FinancialOverview>,
  'year' : bigint,
  'incomeByPaymentMethod' : Array<PaymentMethodSummary>,
  'totalOverview' : FinancialOverview,
}
export interface _SERVICE {
  'addMonthlyIncome' : ActorMethod<[MonthlyIncomeInput], undefined>,
  'addTransaction' : ActorMethod<[TransactionInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authorizeReadOnlyAccess' : ActorMethod<[Principal], undefined>,
  'clearMigratedMonthlyIncomes' : ActorMethod<[], undefined>,
  'migrateMonthlyIncomesToTransactions' : ActorMethod<[], bigint>,
  'deleteMonthlyIncome' : ActorMethod<[bigint, bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'exportData' : ActorMethod<[], ExportData>,
  'getAllBusinessProfilesReadOnly' : ActorMethod<
    [],
    Array<[Principal, BusinessProfile]>
  >,
  'getAllMonthlyIncomes' : ActorMethod<[], Array<MonthlyIncomeInput>>,
  'getAllMonthlyIncomesReadOnly' : ActorMethod<[], Array<MonthlyIncomeInput>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllTransactionsReadOnly' : ActorMethod<[], Array<Transaction>>,
  'getBusinessPerformanceAnalysis' : ActorMethod<
    [BenchmarkPeriod],
    PerformanceAnalysis
  >,
  'getBusinessProfile' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'getCallerBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getDfinityTechnicalAnalysis' : ActorMethod<[], DfinityTechnicalAnalysis>,
  'getDfinityTechnicalReport' : ActorMethod<[], DfinityTechnicalReport>,
  'getDfinityVoiceCommandIssueReport' : ActorMethod<
    [],
    DfinityVoiceCommandIssueReport
  >,
  'getExpenseShareByCategory' : ActorMethod<
    [bigint, bigint],
    Array<ExpenseShare>
  >,
  'getMonthlyIncome' : ActorMethod<[bigint, bigint], bigint>,
  'getMonthlyIncomeCount' : ActorMethod<[bigint, bigint], bigint>,
  'getMonthlyIncomeExpenseByYear' : ActorMethod<
    [bigint],
    Array<MonthlyIncomeExpense>
  >,
  'getMonthlyOverview' : ActorMethod<[bigint, bigint], FinancialOverview>,
  'getMonthlyReport' : ActorMethod<[bigint, bigint], MonthlyReport>,
  'getPdfFinancialReportData' : ActorMethod<[[] | [bigint]], PdfReportData>,
  'getPredictiveAnalysis' : ActorMethod<
    [],
    {
      'projections' : Array<Projection>,
      'historicalData' : Array<[bigint, bigint, bigint, bigint]>,
    }
  >,
  'getTotalMonthlyIncome' : ActorMethod<[bigint, bigint], bigint>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionCountsByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getTransactionsByCategory' : ActorMethod<
    [TransactionType, [] | [ExpenseCategory]],
    Array<Transaction>
  >,
  'getTransactionsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<Transaction>
  >,
  'getTransactionsByFilters' : ActorMethod<
    [
      [] | [TransactionType],
      [] | [ExpenseCategory],
      [] | [PaymentMethod],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Transaction>
  >,
  'getTransactionsByPaymentMethod' : ActorMethod<
    [PaymentMethod],
    Array<Transaction>
  >,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYearComparison' : ActorMethod<[Array<bigint>], Array<YearComparison>>,
  'getYearlyOverview' : ActorMethod<[bigint], FinancialOverview>,
  'getYearlyReport' : ActorMethod<[bigint], YearlyReport>,
  'hasCallerReadOnlyAccess' : ActorMethod<[], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isWakeUpRoutineActive' : ActorMethod<[], boolean>,
  'revokeReadOnlyAccess' : ActorMethod<[Principal], undefined>,
  'runSimulation' : ActorMethod<[number, number], SimulationResult>,
  'saveBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startWakeUpRoutine' : ActorMethod<[], undefined>,
  'updateMonthlyIncome' : ActorMethod<[MonthlyIncomeInput], undefined>,
  'updateTransaction' : ActorMethod<[bigint, TransactionInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];