/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OfferType = IDL.Variant({
  'bar' : IDL.Null,
  'brzaHrana' : IDL.Null,
  'kafic' : IDL.Null,
  'ostalo' : IDL.Null,
  'restoran' : IDL.Null,
});
export const SeasonalActivity = IDL.Variant({
  'oboje' : IDL.Null,
  'zima' : IDL.Null,
  'ljeto' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'offerType' : OfferType,
  'seasonalActivity' : SeasonalActivity,
  'numberOfSeats' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'restaurantName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authorizeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
  'getAllBusinessProfilesReadOnly' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessProfile))],
      ['query'],
    ),
  'getBusinessProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerBusinessProfile' : IDL.Func(
      [],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCallerReadOnlyAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OfferType = IDL.Variant({
    'bar' : IDL.Null,
    'brzaHrana' : IDL.Null,
    'kafic' : IDL.Null,
    'ostalo' : IDL.Null,
    'restoran' : IDL.Null,
  });
  const SeasonalActivity = IDL.Variant({
    'oboje' : IDL.Null,
    'zima' : IDL.Null,
    'ljeto' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'offerType' : OfferType,
    'seasonalActivity' : SeasonalActivity,
    'numberOfSeats' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authorizeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
    'getAllBusinessProfilesReadOnly' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BusinessProfile))],
        ['query'],
      ),
    'getBusinessProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerBusinessProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCallerReadOnlyAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeReadOnlyAccess' : IDL.Func([IDL.Principal], [], []),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };