/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    month: bigint;
    expensesByCategory: Array<CategorySummary>;
    overview: FinancialOverview;
    year: bigint;
    incomeByPaymentMethod: Array<PaymentMethodSummary>;
}
export interface PerformanceDeviation {
    status: DeviationStatus;
    industryAverage: bigint;
    deviationPercentage: number;
    category: string;
    userValue: bigint;
}
export interface PaymentMethodSummary {
    total: bigint;
    paymentMethod: string;
}
export interface MonthlyIncomeInput {
    month: bigint;
    year: bigint;
    amount: bigint;
}
export interface MonthlyIncomeExpense {
    month: bigint;
    year: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
}
export interface ExportData {
    monthlyIncomes: Array<MonthlyIncomeInput>;
    businessProfile?: BusinessProfile;
    transactions: Array<Transaction>;
}
export interface CategorySummary {
    total: bigint;
    category: string;
}
export interface DfinityTechnicalAnalysis {
    title: string;
    issueDescription: string;
    userExperienceImpact: string;
    recommendations: string;
    conclusion: string;
    dataPersistenceFindings: string;
    executiveSummary: string;
    recoveryAttempts: string;
    technicalAnalysis: string;
}
export type BenchmarkPeriod = {
    __kind__: "cumulative";
    cumulative: null;
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: {
        year: bigint;
    };
};
export interface Transaction {
    id: bigint;
    paymentMethod?: PaymentMethod;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory?: ExpenseCategory;
}
export interface ExpenseShare {
    total: bigint;
    share: number;
    category: string;
}
export interface Projection {
    month: bigint;
    year: bigint;
    projectedIncome: bigint;
    projectedProfit: bigint;
    projectedExpenses: bigint;
}
export interface PdfReportData {
    monthlyIncomes: Array<MonthlyIncomeInput>;
    expensesByCategory: Array<CategorySummary>;
    overview: FinancialOverview;
    incomeByPaymentMethod: Array<PaymentMethodSummary>;
    businessProfile?: BusinessProfile;
    transactions: Array<Transaction>;
}
export interface YearComparison {
    year: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
    monthlyData: Array<MonthlyIncomeExpense>;
}
export interface DfinityVoiceCommandIssueReport {
    title: string;
    authenticationIntegrationProblems: string;
    implementationAttemptHistory: string;
    browserCompatibilityIssues: string;
    conclusion: string;
    rootCauseIdentification: string;
    technicalIssueAnalysis: string;
    introduction: string;
    comparativeAnalysis: string;
    connectivityPatternAnalysis: string;
    implementationTimeline: string;
    platformRecommendations: string;
    technicalArchitectureReview: string;
}
export interface FinancialOverview {
    totalIncome: bigint;
    totalExpenses: bigint;
    profit: bigint;
}
export interface TransactionInput {
    paymentMethod?: PaymentMethod;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory?: ExpenseCategory;
}
export interface PerformanceAnalysis {
    diagnosticInfo?: string;
    period: BenchmarkPeriod;
    recommendations: Array<string>;
    profitMarginDeviation: PerformanceDeviation;
    industryBenchmark: IndustryBenchmark;
    userIncome: bigint;
    userProfit: bigint;
    userExpenses: bigint;
    incomeDeviation: PerformanceDeviation;
    expenseDeviations: Array<PerformanceDeviation>;
}
export interface YearlyReport {
    monthlyOverviews: Array<FinancialOverview>;
    year: bigint;
    incomeByPaymentMethod: Array<PaymentMethodSummary>;
    totalOverview: FinancialOverview;
}
export interface IndustryBenchmark {
    revenuePerSeat?: bigint;
    averageIncome: bigint;
    averageExpenses: bigint;
    averageProfitMargin: number;
    expenseCategoryAverages: Array<[string, bigint]>;
}
export interface DfinityTechnicalReport {
    title: string;
    synchronizationImprovements: string;
    dateBoundaryHandling: string;
    summary: string;
    decimalPrecision: string;
    confirmation: string;
    consistencyVerification: string;
    finalVerification: string;
}
export interface SimulationResult {
    totalProjectedExpenses: bigint;
    projections: Array<Projection>;
    totalProjectedIncome: bigint;
    totalProjectedProfit: bigint;
}
export interface BusinessProfile {
    offerType: OfferType;
    seasonalActivity: SeasonalActivity;
    numberOfSeats: bigint;
    location: string;
}
export interface UserProfile {
    name: string;
    restaurantName: string;
}
export enum DeviationStatus {
    withinNormalRange = "withinNormalRange",
    belowAverage = "belowAverage",
    aboveAverage = "aboveAverage"
}
export enum ExpenseCategory {
    rezije = "rezije",
    oprema = "oprema",
    napojnica = "napojnica",
    pice = "pice",
    place = "place",
    ostalo = "ostalo",
    namirnice = "namirnice"
}
export enum OfferType {
    bar = "bar",
    brzaHrana = "brzaHrana",
    kafic = "kafic",
    ostalo = "ostalo",
    restoran = "restoran"
}
export enum PaymentMethod {
    kartica = "kartica",
    gotovina = "gotovina"
}
export enum SeasonalActivity {
    oboje = "oboje",
    zima = "zima",
    ljeto = "ljeto"
}
export enum TransactionType {
    prihod = "prihod",
    rashod = "rashod"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addMonthlyIncome(input: MonthlyIncomeInput): Promise<void>;
    addTransaction(input: TransactionInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authorizeReadOnlyAccess(principal: Principal): Promise<void>;
    deleteMonthlyIncome(year: bigint, month: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    exportData(): Promise<ExportData>;
    getAllBusinessProfilesReadOnly(): Promise<Array<[Principal, BusinessProfile]>>;
    getAllMonthlyIncomes(): Promise<Array<MonthlyIncomeInput>>;
    getAllMonthlyIncomesReadOnly(): Promise<Array<MonthlyIncomeInput>>;
    migrateMonthlyIncomesToTransactions(): Promise<bigint>;
    clearMigratedMonthlyIncomes(): Promise<void>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllTransactionsReadOnly(): Promise<Array<Transaction>>;
    getBusinessPerformanceAnalysis(period: BenchmarkPeriod): Promise<PerformanceAnalysis>;
    getBusinessProfile(user: Principal): Promise<BusinessProfile | null>;
    getCallerBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTime(): Promise<bigint>;
    getDfinityTechnicalAnalysis(): Promise<DfinityTechnicalAnalysis>;
    getDfinityTechnicalReport(): Promise<DfinityTechnicalReport>;
    getDfinityVoiceCommandIssueReport(): Promise<DfinityVoiceCommandIssueReport>;
    getExpenseShareByCategory(startDate: bigint, endDate: bigint): Promise<Array<ExpenseShare>>;
    getMonthlyIncome(year: bigint, month: bigint): Promise<bigint>;
    getMonthlyIncomeCount(year: bigint, month: bigint): Promise<bigint>;
    getMonthlyIncomeExpenseByYear(year: bigint): Promise<Array<MonthlyIncomeExpense>>;
    getMonthlyOverview(month: bigint, year: bigint): Promise<FinancialOverview>;
    getMonthlyReport(month: bigint, year: bigint): Promise<MonthlyReport>;
    getPdfFinancialReportData(year: bigint | null): Promise<PdfReportData>;
    getPredictiveAnalysis(): Promise<{
        projections: Array<Projection>;
        historicalData: Array<[bigint, bigint, bigint, bigint]>;
    }>;
    getTotalMonthlyIncome(year: bigint, month: bigint): Promise<bigint>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getTransactionCountsByCategory(): Promise<Array<[string, bigint]>>;
    getTransactionsByCategory(transactionType: TransactionType, expenseCategory: ExpenseCategory | null): Promise<Array<Transaction>>;
    getTransactionsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Transaction>>;
    getTransactionsByFilters(transactionType: TransactionType | null, expenseCategory: ExpenseCategory | null, paymentMethod: PaymentMethod | null, startDate: bigint | null, endDate: bigint | null): Promise<Array<Transaction>>;
    getTransactionsByPaymentMethod(paymentMethod: PaymentMethod): Promise<Array<Transaction>>;
    getTransactionsByType(transactionType: TransactionType): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getYearComparison(years: Array<bigint>): Promise<Array<YearComparison>>;
    getYearlyOverview(year: bigint): Promise<FinancialOverview>;
    getYearlyReport(year: bigint): Promise<YearlyReport>;
    hasCallerReadOnlyAccess(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isWakeUpRoutineActive(): Promise<boolean>;
    revokeReadOnlyAccess(principal: Principal): Promise<void>;
    runSimulation(incomeGrowthPercentage: number, expenseGrowthPercentage: number): Promise<SimulationResult>;
    saveBusinessProfile(profile: BusinessProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startWakeUpRoutine(): Promise<void>;
    updateMonthlyIncome(input: MonthlyIncomeInput): Promise<void>;
    updateTransaction(id: bigint, input: TransactionInput): Promise<void>;
}
import type { BenchmarkPeriod as _BenchmarkPeriod, BusinessProfile as _BusinessProfile, CategorySummary as _CategorySummary, DeviationStatus as _DeviationStatus, ExpenseCategory as _ExpenseCategory, ExportData as _ExportData, FinancialOverview as _FinancialOverview, IndustryBenchmark as _IndustryBenchmark, MonthlyIncomeInput as _MonthlyIncomeInput, OfferType as _OfferType, PaymentMethod as _PaymentMethod, PaymentMethodSummary as _PaymentMethodSummary, PdfReportData as _PdfReportData, PerformanceAnalysis as _PerformanceAnalysis, PerformanceDeviation as _PerformanceDeviation, SeasonalActivity as _SeasonalActivity, Transaction as _Transaction, TransactionInput as _TransactionInput, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMonthlyIncome(arg0: MonthlyIncomeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMonthlyIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMonthlyIncome(arg0);
            return result;
        }
    }
    async addTransaction(arg0: TransactionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionInput_n1(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionInput_n1(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async authorizeReadOnlyAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.authorizeReadOnlyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authorizeReadOnlyAccess(arg0);
            return result;
        }
    }
    async deleteMonthlyIncome(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMonthlyIncome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMonthlyIncome(arg0, arg1);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async exportData(): Promise<ExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return from_candid_ExportData_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return from_candid_ExportData_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllBusinessProfilesReadOnly(): Promise<Array<[Principal, BusinessProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBusinessProfilesReadOnly();
                return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBusinessProfilesReadOnly();
            return from_candid_vec_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllMonthlyIncomes(): Promise<Array<MonthlyIncomeInput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyIncomes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyIncomes();
            return result;
        }
    }
    async getAllMonthlyIncomesReadOnly(): Promise<Array<MonthlyIncomeInput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyIncomesReadOnly();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyIncomesReadOnly();
            return result;
        }
    }
    async migrateMonthlyIncomesToTransactions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateMonthlyIncomesToTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateMonthlyIncomesToTransactions();
            return result;
        }
    }
    async clearMigratedMonthlyIncomes(): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.clearMigratedMonthlyIncomes();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.clearMigratedMonthlyIncomes();
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllTransactionsReadOnly(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactionsReadOnly();
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactionsReadOnly();
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBusinessPerformanceAnalysis(arg0: BenchmarkPeriod): Promise<PerformanceAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessPerformanceAnalysis(to_candid_BenchmarkPeriod_n33(this.uploadFile, this.downloadFile, arg0));
                return from_candid_PerformanceAnalysis_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessPerformanceAnalysis(to_candid_BenchmarkPeriod_n33(this.uploadFile, this.downloadFile, arg0));
            return from_candid_PerformanceAnalysis_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBusinessProfile(arg0: Principal): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBusinessProfile();
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBusinessProfile();
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n48(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n48(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getDfinityTechnicalAnalysis(): Promise<DfinityTechnicalAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getDfinityTechnicalAnalysis();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDfinityTechnicalAnalysis();
            return result;
        }
    }
    async getDfinityTechnicalReport(): Promise<DfinityTechnicalReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDfinityTechnicalReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDfinityTechnicalReport();
            return result;
        }
    }
    async getDfinityVoiceCommandIssueReport(): Promise<DfinityVoiceCommandIssueReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDfinityVoiceCommandIssueReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDfinityVoiceCommandIssueReport();
            return result;
        }
    }
    async getExpenseShareByCategory(arg0: bigint, arg1: bigint): Promise<Array<ExpenseShare>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseShareByCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseShareByCategory(arg0, arg1);
            return result;
        }
    }
    async getMonthlyIncome(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncome(arg0, arg1);
            return result;
        }
    }
    async getMonthlyIncomeCount(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncomeCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncomeCount(arg0, arg1);
            return result;
        }
    }
    async getMonthlyIncomeExpenseByYear(arg0: bigint): Promise<Array<MonthlyIncomeExpense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncomeExpenseByYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncomeExpenseByYear(arg0);
            return result;
        }
    }
    async getMonthlyOverview(arg0: bigint, arg1: bigint): Promise<FinancialOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyOverview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyOverview(arg0, arg1);
            return result;
        }
    }
    async getMonthlyReport(arg0: bigint, arg1: bigint): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getPdfFinancialReportData(arg0: bigint | null): Promise<PdfReportData> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfFinancialReportData(to_candid_opt_n51(this.uploadFile, this.downloadFile, arg0));
                return from_candid_PdfReportData_n52(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfFinancialReportData(to_candid_opt_n51(this.uploadFile, this.downloadFile, arg0));
            return from_candid_PdfReportData_n52(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPredictiveAnalysis(): Promise<{
        projections: Array<Projection>;
        historicalData: Array<[bigint, bigint, bigint, bigint]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictiveAnalysis();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictiveAnalysis();
            return result;
        }
    }
    async getTotalMonthlyIncome(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalMonthlyIncome(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalMonthlyIncome(arg0, arg1);
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n54(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionCountsByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionCountsByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionCountsByCategory();
            return result;
        }
    }
    async getTransactionsByCategory(arg0: TransactionType, arg1: ExpenseCategory | null): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(to_candid_TransactionType_n5(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n55(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(to_candid_TransactionType_n5(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n55(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByDateRange(arg0, arg1);
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByDateRange(arg0, arg1);
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionsByFilters(arg0: TransactionType | null, arg1: ExpenseCategory | null, arg2: PaymentMethod | null, arg3: bigint | null, arg4: bigint | null): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByFilters(to_candid_opt_n56(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n55(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n58(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n58(this.uploadFile, this.downloadFile, arg4));
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByFilters(to_candid_opt_n56(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n55(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n58(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n58(this.uploadFile, this.downloadFile, arg4));
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionsByPaymentMethod(arg0: PaymentMethod): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByPaymentMethod(to_candid_PaymentMethod_n3(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByPaymentMethod(to_candid_PaymentMethod_n3(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: TransactionType): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n5(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n5(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this.uploadFile, this.downloadFile, result);
        }
    }
    async getYearComparison(arg0: Array<bigint>): Promise<Array<YearComparison>> {
        if (this.processError) {
            try {
                const result = await this.actor.getYearComparison(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYearComparison(arg0);
            return result;
        }
    }
    async getYearlyOverview(arg0: bigint): Promise<FinancialOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getYearlyOverview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYearlyOverview(arg0);
            return result;
        }
    }
    async getYearlyReport(arg0: bigint): Promise<YearlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getYearlyReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYearlyReport(arg0);
            return result;
        }
    }
    async hasCallerReadOnlyAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCallerReadOnlyAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCallerReadOnlyAccess();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isWakeUpRoutineActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isWakeUpRoutineActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isWakeUpRoutineActive();
            return result;
        }
    }
    async revokeReadOnlyAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeReadOnlyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeReadOnlyAccess(arg0);
            return result;
        }
    }
    async runSimulation(arg0: number, arg1: number): Promise<SimulationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.runSimulation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runSimulation(arg0, arg1);
            return result;
        }
    }
    async saveBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfile_n59(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfile_n59(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startWakeUpRoutine(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startWakeUpRoutine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startWakeUpRoutine();
            return result;
        }
    }
    async updateMonthlyIncome(arg0: MonthlyIncomeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyIncome(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: TransactionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_TransactionInput_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_TransactionInput_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BenchmarkPeriod_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BenchmarkPeriod): BenchmarkPeriod {
    return from_candid_variant_n39(uploadFile, downloadFile, value);
}
function from_candid_BusinessProfile_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_DeviationStatus_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviationStatus): DeviationStatus {
    return from_candid_variant_n43(uploadFile, downloadFile, value);
}
function from_candid_ExpenseCategory_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n30(uploadFile, downloadFile, value);
}
function from_candid_ExportData_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): ExportData {
    return from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_IndustryBenchmark_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndustryBenchmark): IndustryBenchmark {
    return from_candid_record_n45(uploadFile, downloadFile, value);
}
function from_candid_OfferType_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferType): OfferType {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid_PaymentMethod_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
function from_candid_PdfReportData_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PdfReportData): PdfReportData {
    return from_candid_record_n53(uploadFile, downloadFile, value);
}
function from_candid_PerformanceAnalysis_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceAnalysis): PerformanceAnalysis {
    return from_candid_record_n36(uploadFile, downloadFile, value);
}
function from_candid_PerformanceDeviation_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceDeviation): PerformanceDeviation {
    return from_candid_record_n41(uploadFile, downloadFile, value);
}
function from_candid_SeasonalActivity_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeasonalActivity): SeasonalActivity {
    return from_candid_variant_n19(uploadFile, downloadFile, value);
}
function from_candid_TransactionType_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid_Transaction_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n22(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(uploadFile, downloadFile, value);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n14(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n24(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpenseCategory]): ExpenseCategory | null {
    return value.length === 0 ? null : from_candid_ExpenseCategory_n29(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthlyIncomes: Array<_MonthlyIncomeInput>;
    businessProfile: [] | [_BusinessProfile];
    transactions: Array<_Transaction>;
}): {
    monthlyIncomes: Array<MonthlyIncomeInput>;
    businessProfile?: BusinessProfile;
    transactions: Array<Transaction>;
} {
    return {
        monthlyIncomes: value.monthlyIncomes,
        businessProfile: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.businessProfile)),
        transactions: from_candid_vec_n20(uploadFile, downloadFile, value.transactions)
    };
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offerType: _OfferType;
    seasonalActivity: _SeasonalActivity;
    numberOfSeats: bigint;
    location: string;
}): {
    offerType: OfferType;
    seasonalActivity: SeasonalActivity;
    numberOfSeats: bigint;
    location: string;
} {
    return {
        offerType: from_candid_OfferType_n16(uploadFile, downloadFile, value.offerType),
        seasonalActivity: from_candid_SeasonalActivity_n18(uploadFile, downloadFile, value.seasonalActivity),
        numberOfSeats: value.numberOfSeats,
        location: value.location
    };
}
function from_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentMethod: [] | [_PaymentMethod];
    transactionType: _TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory: [] | [_ExpenseCategory];
}): {
    id: bigint;
    paymentMethod?: PaymentMethod;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory?: ExpenseCategory;
} {
    return {
        id: value.id,
        paymentMethod: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.paymentMethod)),
        transactionType: from_candid_TransactionType_n26(uploadFile, downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        amount: value.amount,
        expenseCategory: record_opt_to_undefined(from_candid_opt_n28(uploadFile, downloadFile, value.expenseCategory))
    };
}
function from_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diagnosticInfo: [] | [string];
    period: _BenchmarkPeriod;
    recommendations: Array<string>;
    profitMarginDeviation: _PerformanceDeviation;
    industryBenchmark: _IndustryBenchmark;
    userIncome: bigint;
    userProfit: bigint;
    userExpenses: bigint;
    incomeDeviation: _PerformanceDeviation;
    expenseDeviations: Array<_PerformanceDeviation>;
}): {
    diagnosticInfo?: string;
    period: BenchmarkPeriod;
    recommendations: Array<string>;
    profitMarginDeviation: PerformanceDeviation;
    industryBenchmark: IndustryBenchmark;
    userIncome: bigint;
    userProfit: bigint;
    userExpenses: bigint;
    incomeDeviation: PerformanceDeviation;
    expenseDeviations: Array<PerformanceDeviation>;
} {
    return {
        diagnosticInfo: record_opt_to_undefined(from_candid_opt_n37(uploadFile, downloadFile, value.diagnosticInfo)),
        period: from_candid_BenchmarkPeriod_n38(uploadFile, downloadFile, value.period),
        recommendations: value.recommendations,
        profitMarginDeviation: from_candid_PerformanceDeviation_n40(uploadFile, downloadFile, value.profitMarginDeviation),
        industryBenchmark: from_candid_IndustryBenchmark_n44(uploadFile, downloadFile, value.industryBenchmark),
        userIncome: value.userIncome,
        userProfit: value.userProfit,
        userExpenses: value.userExpenses,
        incomeDeviation: from_candid_PerformanceDeviation_n40(uploadFile, downloadFile, value.incomeDeviation),
        expenseDeviations: from_candid_vec_n47(uploadFile, downloadFile, value.expenseDeviations)
    };
}
function from_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DeviationStatus;
    industryAverage: bigint;
    deviationPercentage: number;
    category: string;
    userValue: bigint;
}): {
    status: DeviationStatus;
    industryAverage: bigint;
    deviationPercentage: number;
    category: string;
    userValue: bigint;
} {
    return {
        status: from_candid_DeviationStatus_n42(uploadFile, downloadFile, value.status),
        industryAverage: value.industryAverage,
        deviationPercentage: value.deviationPercentage,
        category: value.category,
        userValue: value.userValue
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revenuePerSeat: [] | [bigint];
    averageIncome: bigint;
    averageExpenses: bigint;
    averageProfitMargin: number;
    expenseCategoryAverages: Array<[string, bigint]>;
}): {
    revenuePerSeat?: bigint;
    averageIncome: bigint;
    averageExpenses: bigint;
    averageProfitMargin: number;
    expenseCategoryAverages: Array<[string, bigint]>;
} {
    return {
        revenuePerSeat: record_opt_to_undefined(from_candid_opt_n46(uploadFile, downloadFile, value.revenuePerSeat)),
        averageIncome: value.averageIncome,
        averageExpenses: value.averageExpenses,
        averageProfitMargin: value.averageProfitMargin,
        expenseCategoryAverages: value.expenseCategoryAverages
    };
}
function from_candid_record_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthlyIncomes: Array<_MonthlyIncomeInput>;
    expensesByCategory: Array<_CategorySummary>;
    overview: _FinancialOverview;
    incomeByPaymentMethod: Array<_PaymentMethodSummary>;
    businessProfile: [] | [_BusinessProfile];
    transactions: Array<_Transaction>;
}): {
    monthlyIncomes: Array<MonthlyIncomeInput>;
    expensesByCategory: Array<CategorySummary>;
    overview: FinancialOverview;
    incomeByPaymentMethod: Array<PaymentMethodSummary>;
    businessProfile?: BusinessProfile;
    transactions: Array<Transaction>;
} {
    return {
        monthlyIncomes: value.monthlyIncomes,
        expensesByCategory: value.expensesByCategory,
        overview: value.overview,
        incomeByPaymentMethod: value.incomeByPaymentMethod,
        businessProfile: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.businessProfile)),
        transactions: from_candid_vec_n20(uploadFile, downloadFile, value.transactions)
    };
}
function from_candid_tuple_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _BusinessProfile]): [Principal, BusinessProfile] {
    return [
        value[0],
        from_candid_BusinessProfile_n14(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    brzaHrana: null;
} | {
    kafic: null;
} | {
    ostalo: null;
} | {
    restoran: null;
}): OfferType {
    return "bar" in value ? OfferType.bar : "brzaHrana" in value ? OfferType.brzaHrana : "kafic" in value ? OfferType.kafic : "ostalo" in value ? OfferType.ostalo : "restoran" in value ? OfferType.restoran : value;
}
function from_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oboje: null;
} | {
    zima: null;
} | {
    ljeto: null;
}): SeasonalActivity {
    return "oboje" in value ? SeasonalActivity.oboje : "zima" in value ? SeasonalActivity.zima : "ljeto" in value ? SeasonalActivity.ljeto : value;
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kartica: null;
} | {
    gotovina: null;
}): PaymentMethod {
    return "kartica" in value ? PaymentMethod.kartica : "gotovina" in value ? PaymentMethod.gotovina : value;
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prihod: null;
} | {
    rashod: null;
}): TransactionType {
    return "prihod" in value ? TransactionType.prihod : "rashod" in value ? TransactionType.rashod : value;
}
function from_candid_variant_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rezije: null;
} | {
    oprema: null;
} | {
    napojnica: null;
} | {
    pice: null;
} | {
    place: null;
} | {
    ostalo: null;
} | {
    namirnice: null;
}): ExpenseCategory {
    return "rezije" in value ? ExpenseCategory.rezije : "oprema" in value ? ExpenseCategory.oprema : "napojnica" in value ? ExpenseCategory.napojnica : "pice" in value ? ExpenseCategory.pice : "place" in value ? ExpenseCategory.place : "ostalo" in value ? ExpenseCategory.ostalo : "namirnice" in value ? ExpenseCategory.namirnice : value;
}
function from_candid_variant_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cumulative: null;
} | {
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    yearly: {
        year: bigint;
    };
}): {
    __kind__: "cumulative";
    cumulative: null;
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: {
        year: bigint;
    };
} {
    return "cumulative" in value ? {
        __kind__: "cumulative",
        cumulative: value.cumulative
    } : "monthly" in value ? {
        __kind__: "monthly",
        monthly: value.monthly
    } : "yearly" in value ? {
        __kind__: "yearly",
        yearly: value.yearly
    } : value;
}
function from_candid_variant_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withinNormalRange: null;
} | {
    belowAverage: null;
} | {
    aboveAverage: null;
}): DeviationStatus {
    return "withinNormalRange" in value ? DeviationStatus.withinNormalRange : "belowAverage" in value ? DeviationStatus.belowAverage : "aboveAverage" in value ? DeviationStatus.aboveAverage : value;
}
function from_candid_variant_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n21(uploadFile, downloadFile, x));
}
function from_candid_vec_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _BusinessProfile]>): Array<[Principal, BusinessProfile]> {
    return value.map((x)=>from_candid_tuple_n32(uploadFile, downloadFile, x));
}
function from_candid_vec_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PerformanceDeviation>): Array<PerformanceDeviation> {
    return value.map((x)=>from_candid_PerformanceDeviation_n40(uploadFile, downloadFile, x));
}
function to_candid_BenchmarkPeriod_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BenchmarkPeriod): _BenchmarkPeriod {
    return to_candid_variant_n34(uploadFile, downloadFile, value);
}
function to_candid_BusinessProfile_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n60(uploadFile, downloadFile, value);
}
function to_candid_ExpenseCategory_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n8(uploadFile, downloadFile, value);
}
function to_candid_OfferType_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferType): _OfferType {
    return to_candid_variant_n62(uploadFile, downloadFile, value);
}
function to_candid_PaymentMethod_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_SeasonalActivity_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeasonalActivity): _SeasonalActivity {
    return to_candid_variant_n64(uploadFile, downloadFile, value);
}
function to_candid_TransactionInput_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n2(uploadFile, downloadFile, value);
}
function to_candid_TransactionType_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(uploadFile, downloadFile, value);
}
function to_candid_opt_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory | null): [] | [_ExpenseCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ExpenseCategory_n7(uploadFile, downloadFile, value));
}
function to_candid_opt_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType | null): [] | [_TransactionType] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionType_n5(uploadFile, downloadFile, value));
}
function to_candid_opt_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod | null): [] | [_PaymentMethod] {
    return value === null ? candid_none() : candid_some(to_candid_PaymentMethod_n3(uploadFile, downloadFile, value));
}
function to_candid_opt_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod?: PaymentMethod;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory?: ExpenseCategory;
}): {
    paymentMethod: [] | [_PaymentMethod];
    transactionType: _TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
    expenseCategory: [] | [_ExpenseCategory];
} {
    return {
        paymentMethod: value.paymentMethod ? candid_some(to_candid_PaymentMethod_n3(uploadFile, downloadFile, value.paymentMethod)) : candid_none(),
        transactionType: to_candid_TransactionType_n5(uploadFile, downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        amount: value.amount,
        expenseCategory: value.expenseCategory ? candid_some(to_candid_ExpenseCategory_n7(uploadFile, downloadFile, value.expenseCategory)) : candid_none()
    };
}
function to_candid_record_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offerType: OfferType;
    seasonalActivity: SeasonalActivity;
    numberOfSeats: bigint;
    location: string;
}): {
    offerType: _OfferType;
    seasonalActivity: _SeasonalActivity;
    numberOfSeats: bigint;
    location: string;
} {
    return {
        offerType: to_candid_OfferType_n61(uploadFile, downloadFile, value.offerType),
        seasonalActivity: to_candid_SeasonalActivity_n63(uploadFile, downloadFile, value.seasonalActivity),
        numberOfSeats: value.numberOfSeats,
        location: value.location
    };
}
function to_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cumulative";
    cumulative: null;
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: {
        year: bigint;
    };
}): {
    cumulative: null;
} | {
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    yearly: {
        year: bigint;
    };
} {
    return value.__kind__ === "cumulative" ? {
        cumulative: value.cumulative
    } : value.__kind__ === "monthly" ? {
        monthly: value.monthly
    } : value.__kind__ === "yearly" ? {
        yearly: value.yearly
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    kartica: null;
} | {
    gotovina: null;
} {
    return value == PaymentMethod.kartica ? {
        kartica: null
    } : value == PaymentMethod.gotovina ? {
        gotovina: null
    } : value;
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    prihod: null;
} | {
    rashod: null;
} {
    return value == TransactionType.prihod ? {
        prihod: null
    } : value == TransactionType.rashod ? {
        rashod: null
    } : value;
}
function to_candid_variant_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferType): {
    bar: null;
} | {
    brzaHrana: null;
} | {
    kafic: null;
} | {
    ostalo: null;
} | {
    restoran: null;
} {
    return value == OfferType.bar ? {
        bar: null
    } : value == OfferType.brzaHrana ? {
        brzaHrana: null
    } : value == OfferType.kafic ? {
        kafic: null
    } : value == OfferType.ostalo ? {
        ostalo: null
    } : value == OfferType.restoran ? {
        restoran: null
    } : value;
}
function to_candid_variant_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeasonalActivity): {
    oboje: null;
} | {
    zima: null;
} | {
    ljeto: null;
} {
    return value == SeasonalActivity.oboje ? {
        oboje: null
    } : value == SeasonalActivity.zima ? {
        zima: null
    } : value == SeasonalActivity.ljeto ? {
        ljeto: null
    } : value;
}
function to_candid_variant_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    rezije: null;
} | {
    oprema: null;
} | {
    napojnica: null;
} | {
    pice: null;
} | {
    place: null;
} | {
    ostalo: null;
} | {
    namirnice: null;
} {
    return value == ExpenseCategory.rezije ? {
        rezije: null
    } : value == ExpenseCategory.oprema ? {
        oprema: null
    } : value == ExpenseCategory.napojnica ? {
        napojnica: null
    } : value == ExpenseCategory.pice ? {
        pice: null
    } : value == ExpenseCategory.place ? {
        place: null
    } : value == ExpenseCategory.ostalo ? {
        ostalo: null
    } : value == ExpenseCategory.namirnice ? {
        namirnice: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
